#!/bin/bash --login
#$ -cwd              # Job will run in the current directory (where you ran qsub)
                     # Nothing specified to request more cores = default 1 core

# Load any required modulefiles
# module load apps/some/example/1.2.3

# Now the commands to be run by the job
wget -r -N -c -np https://physionet.org/files/ptb-xl/1.0.3/